export enum CardActionTypes {
  SET_QUERY = "SET_QUERY",
  FETCH_CARDS_REQUEST = "FETCH_CARDS_REQUEST",
  FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS",
  FETCH_RELATED_CARDS_SUCCESS = "FETCH_RELATED_CARDS_SUCCESS",
  FETCH_CARDS_FAILURE = "FETCH_CARDS_FAILURE",
}
