export enum ImageActionTypes {
  SET_RANDOM_IMAGE = "SET_RANDOM_IMAGE",
  SET_RANDOM_IMAGE_LOADING = "SET_RANDOM_IMAGE_LOADING",
  SET_RANDOM_IMAGE_SUCCESS = "SET_RANDOM_IMAGE_SUCCESS",
  SET_RANDOM_IMAGE_ERROR = "SET_RANDOM_IMAGE_ERROR",
}
